-- AlterTable
ALTER TABLE `transaction` ADD COLUMN `category` ENUM('SALARIO', 'EXTRAS', 'ALUGUEIS', 'MORADIA', 'TRANSPORTE', 'SAUDE', 'EDUCACAO', 'ASSINATURAS', 'ALIMENTACAO', 'CUIDADOS_PESSOAIS', 'OUTROS') NOT NULL DEFAULT 'OUTROS',
    ADD COLUMN `endDate` DATETIME(3) NULL,
    ADD COLUMN `isRecurring` BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE `Goal` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` ENUM('INCOME', 'EXPENSE') NOT NULL,
    `amount` DOUBLE NOT NULL,
    `month` INTEGER NOT NULL,
    `year` INTEGER NOT NULL,
    `userId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Goal` ADD CONSTRAINT `Goal_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
